services:
  api:
    container_name: karrio.api
    image: ghcr.io/karrioapi/server:${KARRIO_TAG}
    restart: unless-stopped
    ports:
      - ${KARRIO_HTTP_PORT}:${KARRIO_HTTP_PORT}
    depends_on:
      - db
      - redis
    environment:
      DEBUG_MODE: "True"
      DETACHED_WORKER: "True"
      SECRET_KEY: ${SECRET_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      KARRIO_HTTP_PORT: ${KARRIO_HTTP_PORT}
      ENABLE_ALL_PLUGINS_BY_DEFAULT: "True"
    volumes:
      - ${KARRIO_PLUGINS:-./plugins}:/karrio/plugins
    healthcheck:
      test: curl --fail http://api:5002/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 5
      start_period: 60s

  worker:
    container_name: karrio.worker
    image: ghcr.io/karrioapi/server:${KARRIO_TAG}
    restart: unless-stopped
    depends_on:
      - db
      - redis
      - api
    environment:
      DEBUG_MODE: "True"
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ENABLE_ALL_PLUGINS_BY_DEFAULT: "True"
    volumes:
      - ${KARRIO_PLUGINS:-./plugins}:/karrio/plugins
    command: "/bin/bash ./worker"

  dashboard:
    container_name: karrio.dashboard
    image: ghcr.io/karrioapi/dashboard:${KARRIO_TAG}
    restart: unless-stopped
    ports:
      - ${DASHBOARD_PORT:-3002}:${DASHBOARD_PORT:-3002}/tcp
    depends_on:
      api:
        condition: service_healthy
        restart: true
    environment:
      AUTH_TRUST_HOST: true
      NEXTAUTH_SECRET: ${JWT_SECRET}
      DASHBOARD_PORT: ${DASHBOARD_PORT:-3002}
      NEXT_PUBLIC_DASHBOARD_URL: ${DASHBOARD_URL}
      NEXT_PUBLIC_KARRIO_PUBLIC_URL: ${KARRIO_PUBLIC_URL}
      KARRIO_URL: http://api:${KARRIO_HTTP_PORT:-5002}

  caddy:
    container_name: karrio.caddy
    image: caddy:2.8.4
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      API_UPSTREAM: "http://api:5002"
      DASHBOARD_UPSTREAM: "http://dashboard:${DASHBOARD_PORT:-3002}"
      DOCS_UPSTREAM: "${DOCS_UPSTREAM:-http://host.docker.internal:3005}"
      CADDY_CERT_DIR: /etc/caddy/certs
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile:ro
      - ../.karrio/certs:/etc/caddy/certs:ro
    depends_on:
      - api
      - dashboard
    extra_hosts:
      - "host.docker.internal:host-gateway"

  maildev:
    container_name: karrio.mail
    image: maildev/maildev
    restart: on-failure
    ports:
      - "1080:1080"
      - "1025:1025"

  db:
    container_name: karrio.db
    image: postgres
    restart: unless-stopped
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data/karrio
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: karrio.redis
    image: redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
